const TodosTypes = {
  FETCH_TODOS_START: 'FETCH_TODOS_START',
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',

  FETCH_TODO_BY_ID_START: 'FETCH_TODO_BY_ID_START',
  FETCH_TODO_BY_ID_SUCCESS: 'FETCH_TODO_BY_ID_SUCCESS',
  FETCH_TODO_BY_ID_FAILURE: 'FETCH_TODO_BY_ID_FAILURE',
};

export default TodosTypes;
